import os
from typing import List, Dict
from datetime import datetime

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN


class PPTGenerator:
    """
    Generates PowerPoint from structured slide content
    """

    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def create_ppt(self, slides: List[Dict]) -> str:
        """
        slides format:
        [
            {
                "title": "Slide Title",
                "bullets": ["point1", "point2", "point3"]
            }
        ]
        """

        prs = Presentation()
        normalized_slides = [self._normalize_slide(slide) for slide in slides]

        if normalized_slides:
            self._add_title_slide(prs, normalized_slides[0])
            normalized_slides = normalized_slides[1:]

        for slide_data in normalized_slides:
            self._add_content_slide(prs, slide_data)

        file_name = f"generated_ppt_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pptx"
        output_path = os.path.join(self.output_dir, file_name)

        prs.save(output_path)

        return output_path

    def _normalize_slide(self, slide: Dict) -> Dict:
        return {
            "title": str(slide.get("title", "")).strip(),
            "bullets": slide.get("bullets", []) or [],
            "theme": str(slide.get("theme", "modern") or "modern").lower(),
            "subtitle": str(slide.get("subtitle", "")).strip(),
        }

    def _get_theme(self, theme_name: str) -> Dict[str, RGBColor]:
        themes = {
            "modern": {
                "bg_color": RGBColor(15, 23, 42),
                "bg_color_light": RGBColor(248, 250, 252),
                "accent": RGBColor(59, 130, 246),
                "accent_soft": RGBColor(96, 165, 250),
                "text_color": RGBColor(255, 255, 255),
                "text_color_dark": RGBColor(17, 24, 39),
                "panel_color": RGBColor(30, 41, 59),
            },
            "creative": {
                "bg_color": RGBColor(20, 83, 45),
                "bg_color_light": RGBColor(249, 250, 251),
                "accent": RGBColor(236, 72, 153),
                "accent_soft": RGBColor(192, 132, 252),
                "text_color": RGBColor(255, 255, 255),
                "text_color_dark": RGBColor(15, 23, 42),
                "panel_color": RGBColor(12, 74, 110),
            },
            "simple": {
                "bg_color": RGBColor(255, 255, 255),
                "bg_color_light": RGBColor(245, 247, 250),
                "accent": RGBColor(37, 99, 235),
                "accent_soft": RGBColor(191, 219, 254),
                "text_color": RGBColor(17, 24, 39),
                "text_color_dark": RGBColor(15, 23, 42),
                "panel_color": RGBColor(229, 231, 235),
            },
        }
        return themes.get(theme_name, themes["modern"])

    def _add_title_slide(self, prs: Presentation, slide_data: Dict) -> None:
        theme = self._get_theme(slide_data["theme"])
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        self._fill_slide_background(slide, theme, title_slide=True)

        width = prs.slide_width
        height = prs.slide_height

        banner = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(0),
            Inches(0),
            width,
            Inches(1.1),
        )
        banner.fill.solid()
        banner.fill.fore_color.rgb = theme["accent"]
        banner.line.fill.background()

        title_box = slide.shapes.add_textbox(Inches(1.0), Inches(1.3), width - Inches(2.0), Inches(2.2))
        title_tf = title_box.text_frame
        title_tf.text = slide_data["title"]
        title_tf.paragraphs[0].font.size = Pt(50)
        title_tf.paragraphs[0].font.bold = True
        title_tf.paragraphs[0].font.color.rgb = theme["text_color"]
        title_tf.paragraphs[0].font.name = "Calibri"

        if slide_data["subtitle"]:
            subtitle_box = slide.shapes.add_textbox(Inches(1.0), Inches(3.7), width - Inches(2.0), Inches(1.0))
            subtitle_tf = subtitle_box.text_frame
            subtitle_tf.text = slide_data["subtitle"]
            subtitle_tf.paragraphs[0].font.size = Pt(24)
            subtitle_tf.paragraphs[0].font.color.rgb = theme["text_color"]
            subtitle_tf.paragraphs[0].font.name = "Calibri"

        footer_box = slide.shapes.add_textbox(Inches(1.0), height - Inches(1.1), width - Inches(2.0), Inches(0.8))
        footer_tf = footer_box.text_frame
        footer_tf.text = "Generated by GenAI PPT Agent"
        footer_tf.paragraphs[0].font.size = Pt(12)
        footer_tf.paragraphs[0].font.color.rgb = theme["text_color"]
        footer_tf.paragraphs[0].alignment = PP_ALIGN.LEFT

    def _add_content_slide(self, prs: Presentation, slide_data: Dict) -> None:
        theme = self._get_theme(slide_data["theme"])
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        self._fill_slide_background(slide, theme, title_slide=False)

        width = prs.slide_width
        height = prs.slide_height

        panel = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(0),
            Inches(0),
            Inches(1.0),
            height,
        )
        panel.fill.solid()
        panel.fill.fore_color.rgb = theme["accent"]
        panel.line.fill.background()

        header = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(1.1),
            Inches(0.6),
            width - Inches(2.3),
            Inches(1.0),
        )
        header.fill.solid()
        header.fill.fore_color.rgb = theme["panel_color"]
        header.line.fill.background()

        title_box = slide.shapes.add_textbox(Inches(1.2), Inches(0.7), width - Inches(2.5), Inches(0.8))
        title_tf = title_box.text_frame
        title_tf.text = slide_data["title"]
        title_par = title_tf.paragraphs[0]
        title_par.font.size = Pt(32)
        title_par.font.bold = True
        title_par.font.color.rgb = theme["text_color_dark"]
        title_par.font.name = "Calibri"

        icon_circle = slide.shapes.add_shape(
            MSO_SHAPE.OVAL,
            width - Inches(1.3),
            Inches(0.75),
            Inches(0.7),
            Inches(0.7),
        )
        icon_circle.fill.solid()
        icon_circle.fill.fore_color.rgb = theme["accent_soft"]
        icon_circle.line.fill.background()

        body_box = slide.shapes.add_textbox(Inches(1.4), Inches(1.8), width - Inches(2.8), height - Inches(3.5))
        body_tf = body_box.text_frame
        body_tf.word_wrap = True
        body_tf.margin_left = Inches(0)
        body_tf.margin_right = Inches(0)
        body_tf.margin_top = Inches(0)
        body_tf.margin_bottom = Inches(0)
        body_tf.clear()

        bullets = slide_data["bullets"]
        if not bullets:
            body_tf.text = "No content available for this slide."
            body_tf.paragraphs[0].font.size = Pt(18)
            body_tf.paragraphs[0].font.color.rgb = theme["text_color_dark"]
            body_tf.paragraphs[0].font.name = "Calibri"
        else:
            for idx, bullet in enumerate(bullets):
                if idx == 0:
                    paragraph = body_tf.paragraphs[0]
                    paragraph.text = bullet
                else:
                    paragraph = body_tf.add_paragraph()
                    paragraph.text = bullet
                paragraph.font.size = Pt(18)
                paragraph.font.color.rgb = theme["text_color_dark"]
                paragraph.font.name = "Calibri"
                paragraph.level = 0
                paragraph.space_after = Pt(8)
                paragraph.bullet = True

        self._add_decorative_footer(slide, theme)

    def _fill_slide_background(self, slide, theme: Dict[str, RGBColor], title_slide: bool) -> None:
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = theme["bg_color" if title_slide else "bg_color_light"]

    def _add_decorative_footer(self, slide, theme: Dict[str, RGBColor]) -> None:
        width = slide.part.package.presentation_part.presentation.slide_width
        height = slide.part.package.presentation_part.presentation.slide_height
        footer = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE,
            Inches(1.1),
            height - Inches(0.8),
            width - Inches(2.2),
            Inches(0.4),
        )
        footer.fill.solid()
        footer.fill.fore_color.rgb = theme["panel_color"]
        footer.line.fill.background()

        footer_text = footer.text_frame
        footer_text.text = "Designed for clarity and impact"
        footer_text.paragraphs[0].font.size = Pt(12)
        footer_text.paragraphs[0].font.color.rgb = theme["text_color_dark"]
        footer_text.paragraphs[0].font.name = "Calibri"
        footer_text.paragraphs[0].alignment = PP_ALIGN.CENTER


# convenience function
_generator = PPTGenerator()


def generate_ppt(slides: List[Dict]) -> str:
    return _generator.create_ppt(slides)